// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1o1YHlBPij3qTGN5Wc3VVgZr0vFgZyNo',
    appId: '1:158940826093:web:eb458d9c83bb99becb7fe4',
    messagingSenderId: '158940826093',
    projectId: 'aman-ghar',
    authDomain: 'aman-ghar.firebaseapp.com',
    storageBucket: 'aman-ghar.firebasestorage.app',
    measurementId: 'G-K8RVQNRK6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbt56B-60DC0YSBFROI29tFM3Ml31pk1k',
    appId: '1:158940826093:android:585b7d128b92c869cb7fe4',
    messagingSenderId: '158940826093',
    projectId: 'aman-ghar',
    storageBucket: 'aman-ghar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYBl8fSJRc2gt0bNXgmLcgT4KhC9yPA4',
    appId: '1:158940826093:ios:b609985317930212cb7fe4',
    messagingSenderId: '158940826093',
    projectId: 'aman-ghar',
    storageBucket: 'aman-ghar.firebasestorage.app',
    iosBundleId: 'com.example.amangharApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYBl8fSJRc2gt0bNXgmLcgT4KhC9yPA4',
    appId: '1:158940826093:ios:b609985317930212cb7fe4',
    messagingSenderId: '158940826093',
    projectId: 'aman-ghar',
    storageBucket: 'aman-ghar.firebasestorage.app',
    iosBundleId: 'com.example.amangharApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1o1YHlBPij3qTGN5Wc3VVgZr0vFgZyNo',
    appId: '1:158940826093:web:1ae4b71c1c4371bccb7fe4',
    messagingSenderId: '158940826093',
    projectId: 'aman-ghar',
    authDomain: 'aman-ghar.firebaseapp.com',
    storageBucket: 'aman-ghar.firebasestorage.app',
    measurementId: 'G-GMLBYC5BL6',
  );
}
